### comparing python list and numpy

#### first we'll compare speed of both list and numpy
#### idea is we'll add two array in both list and numpy and we'll calculate time taken for rough idea

In [2]:
import numpy as np
import time #to measure time

In [6]:
a= [i for i in range (10000000)]
b= [i for i in range (10000000)]

In [12]:
# adding both a and b
start = time.time()
for i in range(len(a)):
    c=a[i]+b[i]
time.time()-start
    

0.8545947074890137

In [13]:
#now lets try on numpy
a1=np.arange(10000000)
b1=np.arange(10000000,20000000)
start =time.time()
c=a1+b1
time.time()-start

0.026459932327270508

In [14]:
0.85/0.02

42.5

### we can clearly see that numpy is 40 times faster than python list due to->
### python list is dynamic and python stores its elements location ,  in reference memory


# now lets check memory

In [16]:
import sys #to get memory size 
a= [i for i in range (100000000)]
sys.getsizeof(a)

835128600

In [17]:
b=np.arange(100000000)
sys.getsizeof(b)

800000112

#### fancy indexing and boolean indexing

In [20]:
a= np.arange(12).reshape(4,3)

In [21]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
#suppose from a matrix we want to get 0 th column , 2nd and 3rd from normal slicing we cannot do this so for this purpose 
#from normal slicing we can get 
a[1::2]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [25]:
# as we can see that by anyhow we can't get 0th column by anyhow so for this issue we need something called as fancy indexing

In [26]:
#in facing indexing what we do is we pass index as list
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
#to make things interesting 
b = np.arange(24).reshape(6,4)

In [30]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
#lets say we want following rows 0,2,3 and 5
b[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [32]:
#now suppose we want to separate 0,1,3 columns
b[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

In [33]:
b[::5,[0,3]]

array([[ 0,  3],
       [20, 23]])

 ##### boolean indexing In this indexing we slice elements according to condition ex-give me even elements from matrix

In [34]:
#we are creating a np array with numbers between 1-100 basically 24 elements between 1-100

In [37]:
#np.random.randint(lower limit,upper limit , total elements we want )
a=np.random.randint(1,100,24).reshape(6,4)

# q1. in 'a' get all elements above 50
#### idea-> we'll compare every element with 50 then from this we know that we'll get result in the form of true or false 
#### now from this true or false we can use it as a mask in our original array

In [41]:
#checking condition
a>50

array([[ True,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [ True, False,  True,  True],
       [False, False,  True, False]])

In [42]:
#adding mask
a[a>50]

array([58, 60, 77, 67, 78, 73, 92], dtype=int32)

#### q2. get all even number from matrix

In [43]:
a[a%2==0]

array([58, 60, 50, 36, 36, 26, 28, 44, 10, 24, 40, 78, 30, 18, 92],
      dtype=int32)

#### q2 get all elements greater than 50 and even

In [52]:
a[(a%2==0) & (a>50)] # we're using $ because we're working on boolean values  in simple terms 'and ' is logical and and $ is bitwise and 

array([58, 60, 78, 92], dtype=int32)

In [53]:
#find all elements not divisible by 7
a[a%7!= 0]

array([58, 60, 50, 36,  9, 11, 33, 36,  3, 26, 37, 44, 10, 24, 67, 40, 78,
       73, 30, 18, 92, 31], dtype=int32)

## Broadcasting ~ most important ,confusing and fundamental topic of numpy