In [1]:
import numpy as np

### this is just example how to deal with missing values more about this we will learn in pandas

### so lets initialize an array with contains nan value basically empty value nan and null is different 

In [4]:
a=np.array([1,2,3,np.nan,4])

#### so we have a built in function that tell us about nan which is np.isnan()

In [5]:
a

array([ 1.,  2.,  3., nan,  4.])

In [6]:
np.isnan(a)

array([False, False, False,  True, False])

#### se this gives us a array in the form of bool . if its nan its returning true. but what we need is values which are not nan so we will use not  bitwise operator

In [17]:
a=a[~np.isnan(a)]

In [18]:
a

array([ True,  True,  True, False,  True])