In [1]:
import numpy as np


In [4]:
a= np.arange(24).reshape(8,3)

In [5]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
#get 0,1,4 rows

a[[0,1,4]]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14]])

In [10]:
# 0,1columns
a[:,[0,1]]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 19],
       [21, 22]])

In [14]:
#3,5 9,11
a[1:4:2,[0,2]]

array([[ 3,  5],
       [ 9, 11]])