In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(2,8)
b=np.arange(16,32).reshape(2,8)

In [3]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [4]:
b

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

# operations on array
#### 1.scaler operations-we work on array with single number

In [5]:
# arithmetic
a+2

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17]])

In [6]:
a*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30]])

In [7]:
# realtional operations
a>1

array([[False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [8]:
a==15

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

# vector operations basically we will work on two or more np array

In [10]:
c=np.random.random((1,16)).reshape(2,8)
a+b+c

array([[16.10414556, 18.21342919, 20.76286857, 22.8243017 , 24.46460642,
        26.95644973, 28.4829572 , 30.96451552],
       [32.02139123, 34.51099129, 36.37730106, 38.09855008, 40.77830783,
        42.76098128, 44.21104767, 46.96274233]])

# Array Functions


In [11]:
a=np.random.random((3,4))

In [33]:
np.round(a*100)

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### max min prod sum

In [14]:
np.max(a)

np.float64(0.8828612107518787)

In [15]:
np.min(a)

np.float64(0.057801502995740384)

In [16]:
np.prod(a)

np.float64(2.5707695810753073e-06)

In [17]:
np.sum(a)

np.float64(5.259855657784437)

In [18]:
np.min(a,axis=1) # in axis 1 represents row and 0 represent column

array([0.0578015, 0.3489128, 0.0964425])

In [19]:
np.max(a,axis=0)

array([0.64483555, 0.3489128 , 0.63829816, 0.88286121])

#### mean median var std

In [20]:
np.mean(a)

np.float64(0.43832130481536974)

In [21]:
np.median(a)

np.float64(0.4048947398041701)

In [22]:
np.var(a)

np.float64(0.06327948007670027)

In [23]:
np.std(a)

np.float64(0.2515541295162937)

#### trigonometric functions

In [24]:
np.sin(a)

array([[0.54254398, 0.2386393 , 0.37754425, 0.05776932],
       [0.60106702, 0.34187632, 0.59582954, 0.68368059],
       [0.41017565, 0.21207055, 0.09629306, 0.77255875]])

#### log exp round floor ceil

In [25]:
np.log(a)

array([[-0.55606254, -1.42310598, -0.94896158, -2.8507405 ],
       [-0.43875996, -1.05293325, -0.44894976, -0.28396337],
       [-0.8612188 , -1.54321388, -2.33880835, -0.12458727]])

In [26]:
np.exp(a)

array([[1.77440049, 1.27247576, 1.47276684, 1.05950467],
       [1.90567361, 1.41752557, 1.89325612, 2.12292364],
       [1.52599498, 1.23824272, 1.10124625, 2.41780768]])

In [27]:
np.round(a) #rounds the value to nearest integer

array([[1., 0., 0., 0.],
       [1., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [28]:
np.floor(a) #gives nearest low integer for ex 5.3 it will give 5 . similarly ceil gives greater value 5.3 ->6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

####  dot product .we know its only possible when first vector column and 2nd vector's row is same . its size will be of row*column

In [29]:
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(4,3)

In [30]:
c=np.dot(a,b)
c

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [31]:
np.shape(c)

(3, 3)

In [32]:
print('the shape of a is',a.shape,'and the shape of b is ',b.shape,'hence shape of c is ',c.shape)

the shape of a is (3, 4) and the shape of b is  (4, 3) hence shape of c is  (3, 3)


In [35]:
a=5.4
np.ceil(a)

np.float64(6.0)