In [1]:
import numpy as np

## today we'll learn about np.sort .
## sorts and gives result in np.array

In [2]:
a= np.random.randint(1,100,15)

In [3]:
a

array([27, 55, 13, 49, 95,  8, 25, 77, 55, 96,  8, 82, 40, 58, 44],
      dtype=int32)

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)

In [5]:
b

array([[30, 64,  8, 48],
       [67, 42, 21, 96],
       [62,  9, 72, 55],
       [37, 22, 38, 15],
       [57, 41, 62, 81],
       [36, 54, 48, 56]], dtype=int32)

In [6]:
np.sort(a)

array([ 8,  8, 13, 25, 27, 40, 44, 49, 55, 55, 58, 77, 82, 95, 96],
      dtype=int32)

In [7]:
np.sort(b)

array([[ 8, 30, 48, 64],
       [21, 42, 67, 96],
       [ 9, 55, 62, 72],
       [15, 22, 37, 38],
       [41, 57, 62, 81],
       [36, 48, 54, 56]], dtype=int32)

## by default np.sort return in ascending values . to do it in decending we will follow this syntax -: np.sort()[::-1]
## with axis 0 we sort acc to column

In [8]:
np.sort(b,axis = 0) #with axis 0 we sort acc to column

array([[30,  9,  8, 15],
       [36, 22, 21, 48],
       [37, 41, 38, 55],
       [57, 42, 48, 56],
       [62, 54, 62, 81],
       [67, 64, 72, 96]], dtype=int32)

In [9]:
np.sort(b,axis = 1) #with axis 1 we sort acc to row

array([[ 8, 30, 48, 64],
       [21, 42, 67, 96],
       [ 9, 55, 62, 72],
       [15, 22, 37, 38],
       [41, 57, 62, 81],
       [36, 48, 54, 56]], dtype=int32)

## np.append add item in last 
## parameter for append function = np.apend(array, values, axis)

In [10]:
np.append(a,20000)

array([   27,    55,    13,    49,    95,     8,    25,    77,    55,
          96,     8,    82,    40,    58,    44, 20000])

In [11]:
np.append(b,np.arange(1,25).reshape(6,4),axis=1)

array([[30, 64,  8, 48,  1,  2,  3,  4],
       [67, 42, 21, 96,  5,  6,  7,  8],
       [62,  9, 72, 55,  9, 10, 11, 12],
       [37, 22, 38, 15, 13, 14, 15, 16],
       [57, 41, 62, 81, 17, 18, 19, 20],
       [36, 54, 48, 56, 21, 22, 23, 24]])

## np.concatenate -- ofcourse concatenates a sequence of aray along with an existing array
## np.concatenate((a,b),axis=0,dtype)

In [12]:
c= np.arange(6).reshape(2,3)

In [13]:
d = np.arange(6,12).reshape(2,3)

In [14]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d),axis =1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [18]:
e=np.random.randint(1,100,25)

In [19]:
f=np.random.randint(1,100,25)

In [20]:
g=np.concatenate((e,f),axis=0)

In [21]:
np.unique(g)

array([ 2,  4, 10, 11, 12, 13, 15, 19, 20, 24, 25, 26, 32, 35, 37, 40, 43,
       45, 48, 49, 50, 51, 52, 53, 55, 57, 67, 68, 69, 71, 73, 75, 81, 87,
       88, 89, 93, 95, 99], dtype=int32)

In [22]:
g.size

50

In [23]:
a=np.array([1,2,3,4,4,56,6,66,6,6,2,1,0])

In [24]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  6, 56, 66])

## np.expand_dims -we can expand demension of an array
## why do we use expand_dims - see basically when we process our data in machine learning algorithms most of them expect data in more dimension so thats why we use expand dims to expand our data dimension

In [25]:
a.shape

(13,)

In [26]:
a=np.expand_dims(a,axis = 0)

In [27]:
np.shape(a)

(1, 13)

In [28]:
a

array([[ 1,  2,  3,  4,  4, 56,  6, 66,  6,  6,  2,  1,  0]])

In [29]:
a=np.arange(1,11).reshape(5,2)

In [30]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
a.shape

(5, 2)

In [32]:
a=np.expand_dims(a,axis=0)

In [33]:
a.shape

(1, 5, 2)

In [34]:
b=np.arange(1,11).reshape(5,2)

In [35]:
b.shape

(5, 2)

In [36]:
b=np.expand_dims(b,axis = 1)

In [37]:
b.shape

(5, 1, 2)

In [38]:
b

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

## np.where return indices of element when certain condition is met.

In [39]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [40]:
np.where(a>1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 2, 2, 3, 3, 4, 4]),
 array([1, 0, 1, 0, 1, 0, 1, 0, 1]))

In [41]:
b=np.array([0,1,1,2,3,5,5])

In [42]:
np.where(b>4)

(array([5, 6]),)

## in np.where we can replace values to if condition is met or not met  by this syntax > np.where(condition,true,false)

In [44]:
np.where(b>4,10,11)

array([11, 11, 11, 11, 11, 10, 10])

## np.argmax returns indices of the max element of the array in particular axis
## np.argmin return indices of the min element of the array
## syntax = np.argmax(arr, axis)

In [51]:
b

array([0, 1, 1, 2, 3, 5, 5])

In [52]:
np.argmax(b)

np.int64(5)

In [53]:
np.argmin(b)

np.int64(0)

# some stats realative functions which are usefull

## np.cumsum = tells cummulative sum over a given array
## np.cumprod = tell cummulative product over a given array
### syntax = np.cumsum(arr, axis) 0 column and 1 row

In [64]:
b=np.arange(0,12).reshape(2,6)

In [65]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:

np.cumsum(b,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16]])

In [67]:
np.cumprod(b,axis =0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 0,  7, 16, 27, 40, 55]])

In [68]:
np.cumprod(b,axis = 1)

array([[     0,      0,      0,      0,      0,      0],
       [     6,     42,    336,   3024,  30240, 332640]])

## np.percentile = gives nth percentile 
### syntax = np.percentile (arr, percentile value which we want)

In [72]:
np.percentile(b,100) # since we have 11 as bigest value in b . so be is the 100th percentile 

np.float64(11.0)

## np.histogram gives data frequency amoung given bins 
### syntax  np.histogram(arr, bins=[])

In [74]:
np.histogram(b, bins =[0,5,10,15])

(array([5, 5, 2]), array([ 0,  5, 10, 15]))

In [75]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## np.corrcoef - return corelation coefficient
### corelation coefficient is nothing but it tell about how data are relative to each other for ex if corelation is 1 means if exp increases salary too increases . values ranges from -1 to 1 , -1 -> negatively corelated . 0 no corealtion , 1 positively co realted

In [76]:
a=np.array([20000,40000,25000,35000])
b=np.array([1,3,2,4])

In [77]:
np.corrcoef(a,b)

array([[1.        , 0.84852814],
       [0.84852814, 1.        ]])

# normal utility function onwards
## np.isin() - used to search for multiple item in an array
## syntax = np.isin(arr , values list )

In [80]:
a

array([20000, 40000, 25000, 35000])

In [81]:
s = [10,1000,20000]
np.isin(a,s)

array([ True, False, False, False])

In [82]:
np.isin(a,1000)

array([False, False, False, False])

In [84]:
# now suppose we want to store values which satisfied conditions 
a[np.isin(a,s)]
#see we got only 20000 since only it satisfied the condition

array([20000])

## np.flip -flips the order of element

In [92]:
a = np.random.randint(1,100,7)

In [93]:
a

array([82, 95, 54, 44, 87, 22, 34], dtype=int32)

In [94]:
np.flip(a)

array([34, 22, 87, 44, 54, 95, 82], dtype=int32)

In [95]:
b = np.random.randint(1,100,18).reshape(3,6)

In [96]:
b

array([[97, 59,  4, 98, 57, 77],
       [73, 83, 81, 43, 37, 37],
       [82,  5, 39, 26, 10, 62]], dtype=int32)

In [97]:
np.flip(b)

array([[62, 10, 26, 39,  5, 82],
       [37, 37, 43, 81, 83, 73],
       [77, 57, 98,  4, 59, 97]], dtype=int32)

In [98]:
np.flip(b,axis=0)

array([[82,  5, 39, 26, 10, 62],
       [73, 83, 81, 43, 37, 37],
       [97, 59,  4, 98, 57, 77]], dtype=int32)

In [99]:
np.flip(b,axis =1)

array([[77, 57, 98,  4, 59, 97],
       [37, 37, 43, 81, 83, 73],
       [62, 10, 26, 39,  5, 82]], dtype=int32)

## np.put  it replaces specific elements of array with given values of array

In [105]:
a

array([110, 540,  54,  44,  87,  22,  34], dtype=int32)

In [106]:
np.put(a,[0,1],[10,50])

In [107]:
a

array([10, 50, 54, 44, 87, 22, 34], dtype=int32)

## np.delete deletes elemments 

In [109]:
np.delete(a,0)

array([50, 54, 44, 87, 22, 34], dtype=int32)

In [111]:
np.delete(a,[0,1,2],axis =0)

array([44, 87, 22, 34], dtype=int32)

# set functions now onwards
## np.union1d
## np.intersect1d
## np.setdiff1d
## np.setxor1d
## np.in1d

In [114]:
a=np.random.randint(1,100,8)

In [115]:
b=np.random.randint(1,100,8)

In [116]:
a


array([78, 71, 67, 50,  4, 98,  4, 92], dtype=int32)

In [117]:
b

array([12, 98, 41, 64, 88, 96, 10, 21], dtype=int32)

In [119]:
np.union1d(a,b)

array([ 4, 10, 12, 21, 41, 50, 64, 67, 71, 78, 88, 92, 96, 98],
      dtype=int32)

In [120]:
np.intersect1d(a,b)

array([98], dtype=int32)

In [123]:
np.setdiff1d(a,b) # elements which are in a but not in b

array([ 4, 50, 67, 71, 78, 92], dtype=int32)

In [126]:
np.setxor1d(a,b) #removes commmon element and keeps other element

array([ 4, 10, 12, 21, 41, 50, 64, 67, 71, 78, 88, 92, 96], dtype=int32)

In [129]:
np.in1d(a,1)

C:\Users\Singh\AppData\Local\Temp\ipykernel_2792\1506200059.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,1)


array([False, False, False, False, False, False, False, False])

## np.clip - exchanges  values with min and max values of the  given range 

In [133]:
a

array([78, 71, 67, 50,  4, 98,  4, 92], dtype=int32)

In [134]:
np.clip(a,a_min=24, a_max=50)

array([50, 50, 50, 50, 24, 50, 24, 50], dtype=int32)