# what is exactly numpy? 

#### it is fundamental package for mathematical computing in python

#### it is a library based on c for performance since in data science or machine learning we generally get large size dataset so we
#### require good performance

#### at core numpy is a n dimensional array(np array) of homogenous data types

# then what is difference between python list and np array?
#### list is dynamic but np array has fixed size.changing size of array will delete the original array and create new array.

#### in np array all elements are required to be of same data type 

In [1]:
import numpy as np

In [2]:
np.array

<function numpy.array>

In [4]:
a= np.array([1,2,3])

In [6]:
a
type(a)

numpy.ndarray

# 2d array


In [25]:
# in numpy the dimension of array depends on number of nested list for an example ([]) 1d , ([[]]) 2d , 3d? you can figure it out ehh? 
a=np.array([[1,3,3],[1,2,3]])
a

array([[1, 3, 3],
       [1, 2, 3]])

In [21]:
# 3d array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.ndim

2

# 3d array

In [22]:
a=np.array([[[1,2],[2,3],[3,4]]])

In [23]:
a

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [24]:
a.ndim

3

# let try 4d array

In [26]:
a = np.array([[[[1,2],[3,4],[5,6]]]])

In [27]:
a

array([[[[1, 2],
         [3, 4],
         [5, 6]]]])

In [28]:
a.ndim

4

## 1d nparray is known as vector , 2d -> matrix ,3d ->tensor and above tensor

### now we will change dtype of nparray

In [32]:
a= np.array([1,2,3],dtype=str)

In [33]:
a

array(['1', '2', '3'], dtype='<U1')

In [34]:
a=np.array([[[1,2,3],[2,3,3]]],dtype=float)

In [35]:
a

array([[[1., 2., 3.],
        [2., 3., 3.]]])

# other way to declare array is np.arange  this basically work likes range func

In [37]:
#arange till 10
a= np.arange(1,11)

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#arange till 10 with steps as 2
a=np.arange(1,11,2)

In [40]:
a

array([1, 3, 5, 7, 9])

In [41]:
#arange fucntion with reshape 
a=np.arange(1,11).reshape(5,2)

In [42]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
# or we can reshape into 2,5  basically row * columns should be equal to number of elements
a=np.arange(1,13).reshape(2,6)

In [45]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [46]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [47]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### np.ones and np.zeros these two are used to quickly initialize array 

In [52]:
a=np.ones((3,5))

In [53]:
b=np.ones(((5,4))

In [56]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### there is also one fucntion named as np.random this is used to quickly initialize array with random given value range

In [63]:
np.random.random((4,3))

array([[0.60449253, 0.98524507, 0.15179005],
       [0.62014169, 0.82293399, 0.94392573],
       [0.13752956, 0.54198922, 0.69528937],
       [0.20505231, 0.43773553, 0.40976503]])

### other way to declare an array is np.linspace

In [65]:
np.linspace(1,10,4) #(lower range , upper range , numberr of elements)


array([ 1.,  4.,  7., 10.])

#### basically what it does is it creates elements with distance between two elements same that why its named as linspace

### other we have is np.identity this is used to create identity matrix instantly

In [67]:
a=np.identity(4)

In [68]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])