In [1]:
import numpy as np

In [29]:
a=np.arange(16).reshape(2,8)
b=np.arange(16,32).reshape(2,8)

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [31]:
b

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

# operations on array
#### 1.scaler operations-we work on array with single number

In [32]:
# arithmetic
a+2

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17]])

In [33]:
a*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30]])

In [34]:
# realtional operations
a>1

array([[False, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [35]:
a==15

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])

In [36]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

# vector operations basically we will work on two or more np array

In [49]:
c=np.random.random((1,16)).reshape(2,8)
a+b+c

array([[16.88055772, 18.38049897, 20.90636247, 22.48321545, 24.81805028,
        26.66901502, 28.82743128, 30.83237291],
       [32.67602034, 34.1018074 , 36.00347408, 38.94593299, 40.19819218,
        42.80279696, 44.53569919, 46.4382641 ]])

# Array Functions


In [82]:
a=np.random.random((3,4))

In [83]:
a=np.round(a*100)

In [84]:
a

array([[52., 60., 44., 12.],
       [52., 22., 18., 44.],
       [91.,  7., 91., 51.]])

#### max min prod sum

In [85]:
np.max(a)

np.float64(91.0)

In [86]:
np.min(a)

np.float64(7.0)

In [87]:
np.prod(a)

np.float64(4.41256101172863e+18)

In [88]:
np.sum(a)

np.float64(544.0)

In [89]:
np.min(a,axis=1) # in axis 1 represents row and 0 represent column

array([12., 18.,  7.])

In [90]:
np.max(a,axis=0)

array([91., 60., 91., 51.])

#### mean median var std

In [91]:
np.mean(a)

np.float64(45.333333333333336)

In [92]:
np.median(a)

np.float64(47.5)

In [93]:
np.var(a)

np.float64(698.5555555555555)

In [94]:
np.std(a)

np.float64(26.430201579926617)

#### trigonometric functions

In [95]:
np.sin(a)

array([[ 0.98662759, -0.30481062,  0.01770193, -0.53657292],
       [ 0.98662759, -0.00885131, -0.75098725,  0.01770193],
       [ 0.10598751,  0.6569866 ,  0.10598751,  0.67022918]])

#### log exp round floor ceil

In [96]:
np.log(a)

array([[3.95124372, 4.09434456, 3.78418963, 2.48490665],
       [3.95124372, 3.09104245, 2.89037176, 3.78418963],
       [4.51085951, 1.94591015, 4.51085951, 3.93182563]])

In [97]:
np.exp(a)

array([[3.83100800e+22, 1.14200739e+26, 1.28516001e+19, 1.62754791e+05],
       [3.83100800e+22, 3.58491285e+09, 6.56599691e+07, 1.28516001e+19],
       [3.31740010e+39, 1.09663316e+03, 3.31740010e+39, 1.40934908e+22]])

In [99]:
np.round(a) #rounds the value to nearest integer

array([[52., 60., 44., 12.],
       [52., 22., 18., 44.],
       [91.,  7., 91., 51.]])

In [102]:
np.floor(a) #gives nearest low integer for ex 5.3 it will give 5 . similarly ceil gives greater value 5.3 ->6

array([[52., 60., 44., 12.],
       [52., 22., 18., 44.],
       [91.,  7., 91., 51.]])

####  dot product .we know its only possible when first vector column and 2nd vector's row is same . its size will be of row*column

In [74]:
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(4,3)

In [77]:
c=np.dot(a,b)
c

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [79]:
np.shape(c)

(3, 3)

In [80]:
print('the shape of a is',a.shape,'and the shape of b is ',b.shape,'hence shape of c is ',c.shape)

the shape of a is (3, 4) and the shape of b is  (4, 3) hence shape of c is  (3, 3)
