## indexing / slicing 

In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)

In [3]:
a2=np.arange(10).reshape(2,5)

In [4]:
a3=np.arange(20).reshape(2,5,2)

In [5]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [8]:
a1[0]

np.int64(0)

In [9]:
a1[-1]

np.int64(9)

In [10]:
a2[-1]

array([5, 6, 7, 8, 9])

In [11]:
a3[-1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

### now as we can see that from sigle indexing we are only able to get the row or column 
### so to get the particular element we need to mention both row and columns 

In [13]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# suppose we need 6 from a2 
a2[1,1]

np.int64(6)

In [15]:
 # amm lets say we need 4
a2[0,4]

np.int64(4)

In [16]:
# for a3
a3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [17]:
a3[1,4,1]

np.int64(19)

## slicing


In [18]:
# from slicing we can select more than 1 item unlike indexng
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
#suppose we want to print element  1-3  in this case we'll use slicing
#we'll first mention row we want to select
a2[0,1:4]

array([1, 2, 3])

In [20]:

a2[1,1:4]

array([6, 7, 8])

In [21]:
#lets try for 3d 
a3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [22]:
a3[1,0:1]

array([[10, 11]])

In [23]:
a3[0,2,0:3]

array([4, 5])

In [24]:
a3[1,3,0:1]

array([16])

In [25]:
#some questions  
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
a2[::,1::2]

array([[1, 3],
       [6, 8]])

In [27]:
b = np.arange(12).reshape(2,6)

In [28]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
b[::,1:4:2]

array([[1, 3],
       [7, 9]])

In [30]:
#3d complex questions on slicing
c=np.arange(16).reshape(2,2,4)

In [31]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [32]:
#suppose we want 1,2,5,6,9,10,13,15
c[:,:,1:3]

array([[[ 1,  2],
        [ 5,  6]],

       [[ 9, 10],
        [13, 14]]])

In [33]:
c=np.arange(27).reshape(3,3,3)

In [34]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
#q1 print matrix in 1 of tensor

c[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [36]:
#q2 print matrix 0th and last in tensor c
c[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
c[0,1]

array([3, 4, 5])

In [38]:
c[1,:,1]

array([10, 13, 16])

In [39]:
#0,2 18,20
c[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### iterations

In [40]:
#to iterate we know its simple we'll simply put for loop
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
for i in a2:
    print (i)

[0 1 2 3 4]
[5 6 7 8 9]


In [43]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
for i in c:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


#### we can see that through loop we can get elements but from matrix i.e apart from verctor we are able to get results in the form of vector 
#### to solve this we can use the n dimensional iterator i.e nditer

In [45]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#### what nditer do is it converts our ndimentional tensor to 1d array i.e vector 

  # transpose and raval reshape 

In [46]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
#converts row into columns and columns into row
a2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [48]:
#other way
np.transpose(a2) 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [49]:
#ravel converts any dimension tensor to 1d i.e vector
np.ravel(a2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### stacking and splitting -> changes on existing array
#### both has two ways horizontal and vertical letss seee both
#### stacking merges two array and splitting is opposite of it

In [52]:
a= np.arange(12).reshape(3,4)
b= np.arange(12,24).reshape(3,4)

In [54]:
#suppose we want to stack both a and b in horizontal way so our array result will be 3,4*2 and we will write np.hstack
np.hstack((a,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
#in vertical we write vstack
#we can stack multiple array this way
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### splitting

In [57]:
c=np.hstack((a,b))

In [62]:
np.hsplit(c,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [66]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [67]:
c

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [68]:
np.vsplit(c,3)

[array([[ 0,  1,  2,  3, 12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7, 16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 20, 21, 22, 23]])]