In [2]:
import numpy as np
import pandas as pd


In [3]:
np.array([1,2])

array([1, 2])

In [4]:
a=np.array([[1,2],[1,2]])

In [5]:
a.shape

(2, 2)

In [6]:
a.ndim

2

In [7]:
c=np.array([[[1,2],[1,2],[1,2]]])

In [8]:
c.ndim

3

In [9]:
np.arange(1,15,2).reshape(7,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13]])

In [10]:
np.arange(1,17).reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [17]:
a=np.arange(1,13).reshape(4,3)
a/100

array([[0.01, 0.02, 0.03],
       [0.04, 0.05, 0.06],
       [0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12]])

In [16]:
np.round(a/100)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.prod(a)

np.int64(479001600)

In [22]:
a=np.arange(0,8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [23]:
np.random.random((1,2))

array([[0.10898795, 0.35292262]])

In [26]:
np.linspace(2,40,4)

array([ 2.        , 14.66666667, 27.33333333, 40.        ])